# Generated by Django 4.2.9 on 2024-02-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_mail', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('delete_yn', models.CharField(max_length=1)),
                ('start_dt', models.DateField()),
                ('end_dt', models.DateField()),
                ('last_dt', models.DateField()),
            ],
        ),
    ]
